// Testes de contrato operacional: independentes da posição visual dos nós.
const {test,before}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {instance}=require('@viz-js/viz');
const root=path.resolve(__dirname,'..');
const dot=fs.readFileSync(path.join(root,'src/fluxo.dot'),'utf8');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'src/catalog.json'),'utf8'));
let nodes,edges;
before(async()=>{const viz=await instance();let result=viz.render(dot,{format:'json0'});assert.equal(result.status,'success');const g=JSON.parse(result.output),byId=new Map(g.objects.map(o=>[o._gvid,o.name]));nodes=new Map(g.objects.filter(o=>o.pos).map(o=>[o.name,o]));edges=g.edges.filter(e=>e.style!=='invis').map(e=>({...e,label:e.xlabel||e.label,from:byId.get(e.tail),to:byId.get(e.head)}))});
// A borda do agrupamento representa a base inteira; a âncora central é geométrica.
const knowledge=['a_tipo','b_entrada','c_tipo','d_tipo','e_sintoma'];
const next=id=>[...edges.filter(e=>e.from===id),...(id==='consultar'?knowledge.map(to=>({to})):[]),...(knowledge.includes(id)?[{to:'orientar'}]:[])];
const edge=(a,b)=>edges.find(e=>e.from===a&&e.to===b);
function reachable(from,blocked=new Set()){let visited=new Set(),todo=[from];while(todo.length){let id=todo.pop();if(visited.has(id)||blocked.has(id))continue;visited.add(id);next(id).forEach(e=>todo.push(e.to))}return visited}

test('entrada e fluxo comum preservados',()=>{assert.equal(nodes.get('crc').label,'Atendimento CRC — 3131-2471');const ids=['crc','whatsapp','interpretar','consultar'];ids.slice(0,-1).forEach((id,i)=>assert.ok(edge(id,ids[i+1])));assert.ok(edge('orientar','resolveu'));assert.equal(edge('resolveu','fim').label,'Sim');assert.equal(edge('resolveu','fila_crc').label,'Não')});
test('revisão acrescenta somente o bloco compacto de sala',()=>{assert.equal(nodes.size,28);assert.equal([...nodes.values()].filter(n=>n.shape==='diamond').length,5)});
test('grafo único e conectado',()=>{const all=reachable('crc');for(const id of nodes.keys())assert.ok(all.has(id),id+' desconectado')});
test('únicos destinos são fim, CRC e Infraestrutura',()=>{assert.deepEqual([...nodes.keys()].filter(id=>!next(id).length).sort(),['fila_crc','fim','infraestrutura']);for(const id of nodes.keys())assert.ok(['fim','fila_crc','infraestrutura'].some(end=>reachable(id).has(end)),id)});
test('reserva revalida nova data e mantém prazos',()=>{assert.equal(edge('d_prazo','d_data').label,'Não');assert.deepEqual(next('d_data').map(e=>e.to),['d_prazo']);assert.equal(nodes.get('d_3').label,'Mínimo de 3 dias úteis');assert.equal(nodes.get('d_10').label,'Mínimo de 10 dias úteis');assert.equal(edge('d_software','d_3').label,'Não');assert.equal(edge('d_software','d_10').label,'Sim');assert.equal(edge('d_prazo','d_formulario').label,'Sim');assert.match(catalog.d_lab.detail,/Corpo Docente e Corpo Técnico Administrativo/);assert.match(nodes.get('d_formulario').label,/@pucminas\.br/);assert.doesNotMatch(dot,/É professor\?|Solicitante é docente\?/)});
test('bloqueio tenta reset e retesta antes do encaminhamento',()=>{assert.deepEqual(next('a_rede').map(e=>e.to),['a_reteste']);assert.ok(edge('a_reteste','a_bloqueada'));assert.equal(edge('a_bloqueada','fila_crc').label,'Sim');assert.match(edge('a_bloqueada','fim').label,/Não/)});
test('credenciais distintas permanecem no catálogo',()=>{assert.match(catalog.a_academica.detail,/codigodepessoa@pucminas\.edu\.br/);assert.match(catalog.a_admin.detail,/senha da rede/);assert.match(catalog.a_admin.detail,/senha de sistemas/);assert.doesNotMatch(dot,/@sga\.pucminas\.br/)});
test('MFA recuperável orienta; sem recuperação ou reset manual vai ao CRC',()=>{assert.equal(edge('a_mfa','a_configurar').label,'Sim');assert.match(edge('a_mfa','fila_crc').label,/Não \/ reset manual/);assert.ok(edge('a_configurar','resolveu'));assert.match(catalog.a_mfa.detail,/backup/)});
test('eventos e projetor preservam seus destinos',()=>{assert.deepEqual(next('c_evento').map(e=>e.to),['fila_crc']);assert.deepEqual(next('e_projetor').map(e=>e.to),['infraestrutura']);assert.equal(nodes.get('infraestrutura').label,'Infraestrutura — 3131-2804')});
test('tópicos documentais não exigem nós próprios',()=>{for(const [id,item] of Object.entries(catalog)){assert.ok(nodes.has(item.nodeId),id);assert.ok(item.sources.length,id)}for(const id of nodes.keys())assert.ok(catalog[id],id);for(const id of ['teams','canvas','mobile','office'])assert.equal(catalog[id].nodeId,'b_entrada');assert.equal(catalog.c_visitante.nodeId,'c_tipo');assert.equal(catalog.d_csc.nodeId,'d_tipo');assert.equal(catalog.e_energia.nodeId,'e_sala');assert.equal(catalog.d_lab.nodeId,'d_software')});
test('saída estática usa um SVG e não publica os originais',()=>{const dist=path.join(root,'dist'),html=fs.readFileSync(path.join(dist,'index.html'),'utf8');assert.equal((html.match(/<svg\b/g)||[]).length,1);assert.doesNotMatch(html,/role="tab"|data-target=/);assert.ok(html.includes('id="search"'));assert.ok(!fs.readdirSync(dist).some(f=>/\.(docx|pdf)$/i.test(f)));assert.ok(fs.existsSync(path.join(dist,'fluxo.dot')))});

test('sala separa fluxo normal e projetor sem ambiguidade',()=>{assert.ok(edge('e_sintoma','e_sala'));assert.ok(edge('e_sintoma','e_projetor'));assert.deepEqual(edges.filter(e=>e.from==='e_sala').map(e=>e.to),['orientar']);assert.ok(!reachable('e_sala').has('infraestrutura'));for(const id of ['e_energia','e_imagem','e_conexao','e_equipamento'])assert.equal(catalog[id].nodeId,'e_sala');assert.deepEqual(edges.filter(e=>e.to==='infraestrutura').map(e=>e.from),['e_projetor'])});
test('espinha alinhada e cinco áreas na ordem horizontal',()=>{const pos=id=>nodes.get(id).pos.split(',').map(Number);const xs=['crc','whatsapp','interpretar','consultar','orientar','resolveu'].map(id=>pos(id)[0]);assert.ok(Math.max(...xs)-Math.min(...xs)<2);const ys=knowledge.map(id=>pos(id)[1]);assert.ok(Math.max(...ys)-Math.min(...ys)<2);knowledge.slice(1).forEach((id,i)=>assert.ok(pos(id)[0]>pos(knowledge[i])[0]));assert.match(dot,/splines=ortho/)});

test('histórico publica quatro snapshots íntegros e aviso sem modificar originais',()=>{const crypto=require('node:crypto'),items=JSON.parse(fs.readFileSync(path.join(root,'archive/manifest.json')));assert.deepEqual(items.map(i=>i.slug),['v4','redesign-1','redesign-2','v1.0']);for(const item of items){const dir=path.join(root,'dist/versoes',item.slug),raw=fs.readFileSync(path.join(dir,'fluxo.html'));assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),item.sha256);const wrapper=fs.readFileSync(path.join(dir,'index.html'),'utf8');assert.match(wrapper,/Versão histórica/);assert.match(wrapper,/href="\.\.\/\.\.\/"/);assert.match(wrapper,/iframe src="fluxo.html"/)}assert.ok(fs.existsSync(path.join(root,'dist/historico/index.html')))});
test('SVG aprovado permanece idêntico ao snapshot V1.0',()=>{const svg=html=>html.match(/<svg\b[\s\S]*?<\/svg>/)[0];assert.equal(svg(fs.readFileSync(path.join(root,'dist/index.html'),'utf8')),svg(fs.readFileSync(path.join(root,'archive/v1.0/fluxo.html'),'utf8')))});
